name: LLY-GLLM CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: |
          pip install pytest  # Ensures pytest is installed
          pytest tests/

  lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Flake8
        run: |
          pip install flake8  # Ensures flake8 is installed
          flake8 .

  build-report:
    runs-on: ubuntu-latest
    needs: 
      - test
      - lint
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run main.py to generate the report
        run: |
          python main.py

      - name: Upload Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: QuantumCircuitReport
          path: QuantumCircuitReport.pdf

  notify:
    runs-on: ubuntu-latest
    needs: build-report
    steps:
      - name: Send notification
        run: echo "The workflow completed successfully!"
